### ISSUE TITLE
Failed to convert: CompilationPipeline.cs:44 error

### ISSUE THREAD

**Issue by EcoEditor** [Unity-Technologies/unityscript2csharp#59] opened 2020-01-20 09:44 UTC
On Unity 2018.1.2f1 - 
Got this error: 
NullReferenceException: Object reference not set to an instance of an object
UnityEditor.Compilation.Assembly.<get_allReferences>m__0 (UnityEditor.Compilation.Assembly a) (at C:/buildslave/unity/build/Editor/Mono/Scripting/ScriptCompilation/CompilationPipeline.cs:44)
System.Linq.Enumerable+SelectArrayIterator`2[TSource,TResult].MoveNext () (at <839a3cb835c04d14aeb58d83bb7bc4bd>:0)
System.Collections.Generic.EnumerableHelpers.IterativeCopy[T] (System.Collections.Generic.IEnumerable`1[T] source, T[] array, System.Int32 arrayIndex, System.Int32 count) (at <839a3cb835c04d14aeb58d83bb7bc4bd>:0)
System.Collections.Generic.EnumerableHelpers.Copy[T] (System.Collections.Generic.IEnumerable`1[T] source, T[] array, System.Int32 arrayIndex, System.Int32 count) (at <839a3cb835c04d14aeb58d83bb7bc4bd>:0)
System.Linq.Enumerable+Concat2Iterator`1[TSource].ToArray () (at <839a3cb835c04d14aeb58d83bb7bc4bd>:0)
System.Linq.Enumerable.ToArray[TSource] (System.Collections.Generic.IEnumerable`1[T] source) (at <839a3cb835c04d14aeb58d83bb7bc4bd>:0)
UnityEditor.Compilation.Assembly.get_allReferences () (at C:/buildslave/unity/build/Editor/Mono/Scripting/ScriptCompilation/CompilationPipeline.cs:44)
UnityScript2CSharpRunner.ReferencesFromAssembly (UnityEditor.Compilation.Assembly a) (at Assets/UnityScript2CSharp/Editor/UnityScript2CSharpRunner.cs:294)
System.Linq.Enumerable+SelectManySingleSelectorIterator`2[TSource,TResult].MoveNext () (at <839a3cb835c04d14aeb58d83bb7bc4bd>:0)
System.Linq.Enumerable+WhereEnumerableIterator`1[TSource].MoveNext () (at <839a3cb835c04d14aeb58d83bb7bc4bd>:0)
System.Linq.Enumerable+DistinctIterator`1[TSource].MoveNext () (at <839a3cb835c04d14aeb58d83bb7bc4bd>:0)
UnityScript2CSharpRunner.ComputeConverterCommandLineArguments (System.Boolean verboseLogging) (at Assets/UnityScript2CSharp/Editor/UnityScript2CSharpRunner.cs:268)
UnityScript2CSharpRunner.RunConverter (System.String converterPath) (at Assets/UnityScript2CSharp/Editor/UnityScript2CSharpRunner.cs:180)
UnityScript2CSharpRunner.Convert () (at Assets/UnityScript2CSharp/Editor/UnityScript2CSharpRunner.cs:97)

What can it be? 
Thank you

**Comment by EcoEditor** [comment] 2020-01-22 10:06
Hello @adrianoc 
After opening in unity 2018.1.9 the issue disappeared.
The new issue is "Ambiguous reference" - I've tried to solve it by writing at the beginning of the script 
"import UnityEngine" but it gives me the ambiguous reference for the following: 
Vecotr3,
Range,
SpringJoint,
Camera,
AudioClip,
AudioSource,
Material,
RigidBody,
Collider

basically all the UnityEngine related items
How would you solve that?

Thank you

**Comment by adrianoc-unity3d** [comment] 2020-01-29 16:31
Hi, did not realized you have filled an issue (for reference, this issue were being discussed at https://forum.unity.com/threads/unityscript-2-csharp-conversion-tool.487753/page-4#post-5399760).

It looks like we are adding references to 2 or more assemblies containing the same types.

As I commented in the forum thread please share your Editor.log when you have the time. 

Note: please use @adrianoc-unity3d handle instead of @adrianoc (the later is my personal user)

**Comment by adrianoc-unity3d** [comment] 2020-02-24 18:42
@awiebe can you share your Editor.log ?

**Comment by adrianoc-unity3d** [comment] 2021-05-17 13:22
Closing issue (cannot reproduce)

**Closed as completed by adrianoc-unity3d** 2021-05-17 13:22 UTC
