### ISSUE TITLE
private enum in js monobehaviour causes problem

### ISSUE THREAD

**Issue by andypoly** [Unity-Technologies/unityscript2csharp#9] opened 2017-09-08 08:50 UTC
private enum needs to stays inside monobehaviour class after conversion buts ends up outside C# class causing error

```
//js test
#pragma strict

private enum ETest {e1,e2,e3}

function Start () 
{

}

```

**Comment by adrianoc-unity3d** [comment] 2017-09-08 13:32
I assume the problem is that the converted enum is marked as **private** right? If this is the problem we can either promote it to **public** (not ideal) or, as you said, declare **inner types** as such in the converted code. I'll investigate it next week

**Comment by andypoly** [comment] 2017-09-08 13:59
Thanks. The issue is that it ends up outside the monobehaviour class, not inside as it is above. It should be marked private still.
Not hard to fix it manually but it's incorrect.

**Comment by adrianoc-unity3d** [comment] 2017-09-19 09:04
@andyz There are 2 different aspects of this issue:

1. Actually US compiler does not emit **ETest** as an inner type; in this specific case it simply change its accessibility to **internal**.

2. BTOH, if you declare the following US code:

        class Foo
        {
            private enum BarEnum {}
        }

then, **BarEnum** will be emitted as an _inner type_.

The converter already handles *2* as expected.

Commit #336fe2e95a1b4951cb6bf0630152c4c5649e3a9b implements rule **1**.

**Closed as completed by adrianoc-unity3d** 2017-09-19 09:04 UTC
